[package]
name = "ironsign"
version = "0.1.0"
edition = "2024"

[dependencies]
cggmp21 = { version = "0.6.2", features = ["curve-secp256k1"] }
cggmp24 = { version = "0.7.0-alpha.3", features = ["curve-secp256k1"] }
round-based = { version = "0.4.1", features = ["sim"] }
sha2 = "0.10.9"
rand = "0.8"
futures = "0.3.31"
hex = "0.4.3"
anyhow = "1.0.100"
tokio = { version = "1.48.0", features = ["time", "rt-multi-thread", "macros", "sync"] }
rmp-serde = "1.3.1"
